#!/bin/bash

### BEGIN INIT INFO
# Provides:        tomcat
# Required-Start:  $network
# Required-Stop:   $network
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start/Stop Tomcat server
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
VERSION=8.5.0
start() {
 /bin/su - tomcat -c /usr/share/tomcat8/apache-tomcat-$VERSION/bin/startup.sh
}

stop() {
 /bin/su - tomcat -c /usr/share/tomcat8/apache-tomcat-$VERSION/bin/shutdown.sh 
}

case $1 in
  start|stop) $1;;
  restart) stop; start;;
  *) echo "Run as $0 <start|stop|restart>"; exit 1;;
esac
